# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.hostname = "dwgd-box"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y docker.io wireguard
        usermod -aG docker vagrant
    SHELL
end
