name: Build dwgd binary

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build binary
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm64, amd64]

    env:
      GOOS:   ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
          go-version-file: 'go.mod'
          cache: true 

    - name: Build binary
      run: |
        go build -ldflags "-X main.Version=${{ steps.release.outputs.tag_name }}" -o bin/dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }} cmd/dwgd.go

    - name: Create archive
      run: |
        tar -czvf bin/dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }}.tar.gz bin/dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }}

    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }}.tar.gz
        path: bin/dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release artifact
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.release.outputs.tag_name }}
        release_name: Release ${{ steps.release.outputs.tag_name }}
        draft: false
        prerelease: false
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: bin/dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }}.tar.gz
        asset_name: dwgd-${{ steps.release.outputs.tag_name }}-${{ env.goos }}-${{ env.goarch }}.tar.gz
        asset_content_type: application/gzip
